#include "../utils.h"

#include <fstream>
#include <stdexcept>

namespace graph_colouring {

void write_coloring(const std::string &path, const Graph &graph, const std::vector<int> &colors) {
	if (static_cast<int>(colors.size()) != graph.vertex_count) {
		throw std::invalid_argument("Colour vector size does not match vertex count");
	}

	std::ofstream output(path);
	if (!output.is_open()) {
		throw std::runtime_error("Failed to open colouring output file: " + path);
	}

	output << "c colouring generated by benchmark framework\n";
	output << "p edge " << graph.vertex_count << ' ' << graph.edge_count << "\n";
	for (int v = 0; v < graph.vertex_count; ++v) {
		output << "v " << (v + 1) << ' ' << colors[v] << "\n";
	}
}

}  // namespace graph_colouring
